### ISSUE TITLE
Warning: invalid next.config.js options detected

### ISSUE THREAD

**Issue by devuxer** [SolidZORO/next-plugin-antd-less#105]
When I start my Next.js app, I receive this warning:

```
warn  - Invalid next.config.js options detected: 
[
  {
    "instancePath": "",
    "schemaPath": "#/additionalProperties",
    "keyword": "additionalProperties",
    "params": {
      "additionalProperty": "lessVarsFilePath"
    },
    "message": "must NOT have additional properties"
  }
]
See more info here: https://nextjs.org/docs/messages/invalid-next-config
```

My next.config.js file looks like this:

```js
const withAntdLess = require("next-plugin-antd-less");

const config = {
    lessVarsFilePath: "./src/front-end/styles/antd-variables.less",

    webpack(config) {
        return config;
    },

    images: {
        domains: ["images.ctfassets.net"],
    },
};

module.exports = withAntdLess(config);

```

**Comment by mikerudge** [comment]
+1

**Comment by madmed88** [comment]
I started seeing similar errors when I upgraded to next 12.2.2, I went back to version 12.2.0 and the errors went away. There is a similar issue in the next.js repo https://github.com/vercel/next.js/issues/38967, it looks like it was fixed in 12.2.3 but I did not test it yet.

**Comment by peterjurco** [comment]
I also started to experience these messages after update of Next. It seems that even Next 12.2.4 hasn't fixed that yet.

**Comment by kasvith** [comment]
yep still on next 12.2.4

**Comment by Webbrother** [comment]
The same for `12.2.5`

**Comment by MarkLyck** [comment]
This seems to be more of a problem with `next-plugin-antd-less` than `next` itself.

I think in 12.2.2 next added warnings for extending the config with other keys, and this is a plugin that does that but shouldn't.

Still happening in next 12.3.1 and this seems to be abandoned?

**Comment by 0fan** [comment]
+1

**Comment by samyarkd** [comment]
Same issue, anyone found any solutions for this? And should i be worried about this ?

**Comment by kasvith** [comment]
Upgrade to latest Ant Design Version, You may not need this anymore(can configure designs with a provider)

**Comment by samyarkd** [comment]
> Upgrade to latest Ant Design Version, You may not need this anymore(can configure designs with a provider)

By latest ants version you version 5?

Well Im afraid to mess stuff up by upgrading

**Comment by kasvith** [comment]
> By latest ants version you version 5?

Yeah, for my usecase we had also some breaking changes. But did it anyway because it was annoying
